import Link from 'next/link';

export default function PrivacyPage() {
    return (
        <div className="space-y-12 animate-in fade-in duration-700">

            <header className="space-y-4 border-b border-black/10 pb-8">
                <h1 className="text-4xl md:text-5xl font-medium uppercase tracking-tighter text-black">Privacy Policy</h1>
                <div className="flex flex-wrap items-center gap-4 text-[10px] font-mono text-gray-400 uppercase tracking-widest">
                    <span>Data Protection & GDPR</span>
                    <span className="w-1 h-1 bg-black/20 rounded-full" />
                    <span>Effective: May 2024</span>
                </div>
            </header>

            <div className="space-y-10 text-sm text-gray-500 font-light leading-relaxed">

                {/* ENTERPRISE HIGHLIGHT BLOCK */}
                <div className="relative p-6 md:p-8 border border-emerald-500/20 bg-emerald-50/50 overflow-hidden rounded-xl shadow-sm">

                    <div className="relative z-10 flex gap-6">
                        <div className="space-y-2">
                            <p className="text-xs md:text-sm text-emerald-900 font-medium leading-relaxed tracking-tight">
                                Pytja is engineered to leave no unauthorized footprints. We do not monetize data, deploy trackers, or collect unnecessary telemetry. All operations are local-first by design.
                            </p>
                        </div>
                    </div>
                </div>

                <section className="space-y-4">
                    <h2 className="text-xl font-bold uppercase tracking-tight text-black">1. Controller Identity</h2>
                    <p>
                        The responsible party (Data Controller) for data processing on this website, pursuant to the General Data Protection Regulation (GDPR), is the entity listed in our <Link href="/legal/imprint" className="text-black font-medium hover:text-blue-600 underline decoration-black/20 transition-colors">Imprint</Link>.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-xl font-bold uppercase tracking-tight text-black">2. Data Collection on our Website</h2>
                    <div className="space-y-6">
                        <div className="p-5 border border-black/5 bg-white rounded-lg shadow-sm">
                            <h3 className="text-black font-bold uppercase tracking-widest text-[11px] mb-2">Server Log Files</h3>
                            <p>
                                The provider of the pages automatically collects and stores information in so-called server log files, which your browser automatically transmits to us. These include: browser type/version, operating system, referrer URL, hostname of the accessing computer, and time of the server request. This data is technically necessary for stability and security. The legal basis for this is Art. 6 (1) (f) GDPR.
                            </p>
                        </div>
                        <div className="p-5 border border-black/5 bg-white rounded-lg shadow-sm">
                            <h3 className="text-black font-bold uppercase tracking-widest text-[11px] mb-2">Contact Forms</h3>
                            <p>
                                If you send us inquiries via the contact form, your details from the inquiry form, including the contact details you provided there, will be stored by us strictly for the purpose of processing the inquiry. We do not pass on this data without your explicit consent (Art. 6 (1) (b) GDPR).
                            </p>
                        </div>
                    </div>
                </section>

                <section className="space-y-4">
                    <h2 className="text-xl font-bold uppercase tracking-tight text-black">3. Pytja Software Telemetry</h2>
                    <p>
                        The Pytja software (CLI and Kernel) operates primarily in a decentralized, air-gapped capacity. Any telemetry, crash reporting, or diagnostic data generated by the software remains local by default. We do <strong className="text-black">not</strong> monitor your database credentials, queries, or returned datasets. Any future network telemetry will be strictly opt-in.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-xl font-bold uppercase tracking-tight text-black">4. Cookies & Analytics</h2>
                    <p>
                        We do <strong className="text-black">not</strong> use privacy-invasive tracking cookies, retargeting pixels, or third-party analytics tools (such as Google Analytics) on this marketing site. Pytja operates on a strict privacy-first basis. Any session management relies solely on technically necessary, local storage mechanisms.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-xl font-bold uppercase tracking-tight text-black">5. Your GDPR Rights</h2>
                    <p>
                        As a data subject under the GDPR, you possess the following rights regarding your personal data:
                    </p>
                    <ul className="list-disc pl-5 space-y-2 text-gray-600 marker:text-black/30">
                        <li><strong className="text-black">Right to Access:</strong> Request information about your stored data, its origin, and its recipients.</li>
                        <li><strong className="text-black">Right to Rectification:</strong> Request correction of inaccurate data.</li>
                        <li><strong className="text-black">Right to Erasure:</strong> Request deletion of your data, provided no statutory retention obligations apply.</li>
                        <li><strong className="text-black">Right to Restrict Processing:</strong> Request the limitation of data processing under specific conditions.</li>
                        <li><strong className="text-black">Right to Data Portability:</strong> Receive data you provided in a structured, standard format.</li>
                    </ul>
                </section>
            </div>
        </div>
    );
}